server_host: "irc.utonet.org"
server_port: 6667
bot_nickname: shamelessbot
log_channels:
    - "#shameless"
feed_interval: 15 #minutes
# ping the server every 30 seconds to recover from dropped connections
TCP keepalive: 30 seconds

# set a rate limit on outgoing messages in messages per second
message rate limit: 2.5
